spring:
  application:
    name: eureka-client2
server:
  port: 10102
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    region: double
    availabilityZones:
      double: defaultZone,serverZone
    serviceUrl:
      defaultZone: http://localhost:10002/eureka/
      serverZone: http://localhost:10001/eureka/
feign:
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 5000
graybunny:
  instance:
    grayEnroll: true #是否在启动后自动注册成灰度实例
  serverUrl: http://localhost:10202 #灰度服务端的url

logging:
  level:
    root: DEBUG